security:
    providers:
        devices_in_memory:
            memory: null

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            stateless: true
            provider: devices_in_memory
            custom_authenticators:
                - App\Infrastructure\Http\Security\DeviceTokenAuthenticator

    access_control:
        - { path: ^/health$, roles: PUBLIC_ACCESS }
        - { path: ^/api$, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/devices/register$, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1, roles: ROLE_DEVICE }

when@test:
    security:
        firewalls:
            main:
                stateless: true
